from typing import Protocol


class Repository[T](Protocol):
    def __init__(self) -> None: ...

    def add(self, item: T) -> T: ...

    def get_by_id(self, id: int) -> T | None: ...

    def get_all(self) -> list[T]: ...

    def update(self, id: int, updated_item: T) -> T | None: ...

    def delete(self, id: int) -> bool: ...
